### ISSUE TITLE
Interfacing LMP91000 with arduino

### ISSUE THREAD

**Issue by Ashwini-Shankar** [LinnesLab/LMP91000#2]
Can we completely interface LMP91000 with arduino?
If yes, how do we do it?

**Comment by hoilett** [comment]
Yes. You can find the connections here: https://github.com/LinnesLab/LMP91000/blob/master/README.md
and in the LMP91000's datasheet: https://www.ti.com/lit/ds/symlink/lmp91000.pdf

**Comment by Ashwini-Shankar** [comment]
Can we interface LMP91000EVM with Arduino? (without communication board)
How will the connections be in this case?

Thank you.

**Comment by ramakrishna722** [comment]
Respected sir,
interfaced Arduino mega with LMP91000, but how to see the output data using LMP91000 AFE software. how to use ANALOG Front end software to interface with LMP91000 and see output data for chronoamperometry and other cyclic voltammetry.
https://user-images.githubusercontent.com/76556368/103086388-86caff80-460a-11eb-83c5-8f152e972c23.jpg.
https://user-images.githubusercontent.com/76556368/103087747-8896c200-460e-11eb-94b5-0f39e590cb4a.jpg.
https://user-images.githubusercontent.com/76556368/103087775-9ba99200-460e-11eb-8557-5102d377ec8a.jpg
https://user-images.githubusercontent.com/76556368/103087789-a8c68100-460e-11eb-8433-65b4e15924f0.jpg.

**Comment by hoilett** [comment]
@Ashwini-Shankar If you're talking about this board (https://www.ti.com/tool/LMP91000EVM), yes you can interface it with the Arduino. You'll need the same connections (SDA, SCL, 3V3, DGND, etc) described in the README (https://github.com/LinnesLab/LMP91000/blob/master/README.md). Just look for where those connections are labeled on the LMP91000EVM board.

@ramakrishna722 I don't think you can use the Arduino Mega with the LMP91000 AFE software. You probably need the SPIO4 board to use the software.

**Comment by ramakrishna722** [comment]
respected sir,
so how to use same codes u mentioned in ur profile. how to see the output when we interface arduino with LMP91000 and see the output for ELECTROCEMICAL IMPEDANCE SPECTROSCOPY.

**Comment by ramakrishna722** [comment]
how to make electrochemical impedance spectroscopy by using LMP91000 potentiostat by interfacing with the arduino 
and where to see output

**Comment by hoilett** [comment]
@ramakrishna722 I don't have any example code electrochemical impedance spectroscopy (EIS). I think I could get something working up to 1-2 kHz, but that's about it.

**Comment by ramakrishna722** [comment]
I think I could get something working up to 1-2 kHz..pls can u give up to this ...i have to implement ELECTROCHEMICAL IMPEDANCE SPECTROSCOPY...

**Comment by hoilett** [comment]
@ramakrishna722 I don't have time to attempt this in the foreseeable future, so I don't know when EIS will be an available feature. Feel free to give it a try. You can find some attempts at doing EIS with my KickStat device:

repo location here: https://github.com/LinnesLab/KickStat-Paper-Firmware
firmware here (line 1144): https://github.com/LinnesLab/KickStat-Paper-Firmware/blob/master/KickStat/Firmware/MiniStatButtonCell/MiniStatButtonCell.ino

**Comment by ramakrishna722** [comment]
TQ SO MUCH SIR

**Comment by hoilett** [comment]
@ramakrishna722 no problem. Thanks for asking.
